on:
  workflow_dispatch:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'

# Continuous integration
name: build

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PZ_VERSION: "41.76"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      # Cache Project Zomboid classes
      - name: Read Zomboid classes cache
        id: pz-cache
        uses: actions/cache@v2
        with:
          path: ./lib/
          key: PZ-${{ env.PZ_VERSION }}-${{ secrets.CACHE_VERSION }}
      # Install Project Zomboid classes
      - name: Install Zomboid classes
        if: steps.pz-cache.outputs.cache-hit != 'true'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "mlem/zomboid"
          version: "tags/v${{ env.PZ_VERSION }}"
          file: "zomboid-${{ env.PZ_VERSION }}.jar"
          target: "lib/zomboid.jar"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # Cache Project Zomboid classes
      - name: Cache Zomboid classes
        if: steps.pz-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ./lib/
          key: PZ-${{ env.PZ_VERSION }}-${{ secrets.CACHE_VERSION }}
      # Apply correct permissions for lib directory
      - name: Apply directory permissions
        run: sudo chmod a+rwx ./lib
      # Install PZ to local maven Repo
      - name: Install PZ to local maven repo
        run: mvn install:install-file -Dfile=./lib/zomboid.jar -DgroupId=zomboid -DartifactId=zomboid -Dversion=${{ env.PZ_VERSION }} -Dpackaging=jar
      # Build jar file
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # build zip/tar file and deploy it
      - name: Publish to GitHub Packages Apache Maven
        run: mvn --projects pz-mod -B assembly:single
      # Upload dist artifacts as run artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
           pz-mod/target/*.jar
           pz-mod/target/*.tar
           pz-mod/target/*.zip
           
